# Generated by Django 3.1.1 on 2020-09-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuickList',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='主键')),
                ('itemName', models.CharField(db_column='item_name', max_length=50, verbose_name='待办事项')),
                ('dealTime', models.DateTimeField(db_column='deal_time', verbose_name='处理时间')),
                ('userNo', models.CharField(db_column='user_no', max_length=10, verbose_name='用户账户')),
                ('userName', models.CharField(db_column='user_name', max_length=10, verbose_name='用户姓名')),
                ('orderNo', models.PositiveSmallIntegerField(db_column='order_no', verbose_name='顺序号')),
                ('complateFlag', models.NullBooleanField(db_column='complete_flag', verbose_name='完成情况：0：未完成；1：已完成')),
                ('complateRemark', models.CharField(db_column='complete_remark', max_length=500, verbose_name='完成备注')),
                ('createTime', models.DateTimeField(db_column='create_time', verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(db_column='update_time', verbose_name='更新时间')),
            ],
            options={
                'db_table': 'biz_quick_list',
            },
        ),
    ]
